// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// ServerUrlHttpspurelymailCom defines the Server URL for
const ServerUrlHttpspurelymailCom = "https://purelymail.com"

// AddDomainRequest defines model for AddDomainRequest.
type AddDomainRequest struct {
	DomainName string `json:"domainName"`
}

// ApiDomainDnsSummary defines model for ApiDomainDnsSummary.
type ApiDomainDnsSummary struct {
	PassesDkim  *bool `json:"passesDkim,omitempty"`
	PassesDmarc *bool `json:"passesDmarc,omitempty"`
	PassesMx    *bool `json:"passesMx,omitempty"`
	PassesSpf   *bool `json:"passesSpf,omitempty"`
}

// ApiDomainInfo defines model for ApiDomainInfo.
type ApiDomainInfo struct {
	AllowAccountReset     *bool                `json:"allowAccountReset,omitempty"`
	DnsSummary            *ApiDomainDnsSummary `json:"dnsSummary,omitempty"`
	IsShared              *bool                `json:"isShared,omitempty"`
	Name                  *string              `json:"name,omitempty"`
	SymbolicSubaddressing *bool                `json:"symbolicSubaddressing,omitempty"`
}

// CheckCreditResponse defines model for CheckCreditResponse.
type CheckCreditResponse struct {
	Result *struct {
		Credit *string `json:"credit,omitempty"`
	} `json:"result,omitempty"`
}

// CreateAppPassword defines model for CreateAppPassword.
type CreateAppPassword struct {
	Name       *string `json:"name,omitempty"`
	UserHandle string  `json:"userHandle"`
}

// CreateAppPasswordResponse defines model for CreateAppPasswordResponse.
type CreateAppPasswordResponse struct {
	Result *struct {
		AppPassword *string `json:"appPassword,omitempty"`
	} `json:"result,omitempty"`
}

// CreateRoutingRequest defines model for CreateRoutingRequest.
type CreateRoutingRequest struct {
	Catchall        *bool    `json:"catchall,omitempty"`
	DomainName      string   `json:"domainName"`
	MatchUser       string   `json:"matchUser"`
	Prefix          bool     `json:"prefix"`
	TargetAddresses []string `json:"targetAddresses"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	UserName string `json:"userName"`
}

// DeleteAppPasswordRequest defines model for DeleteAppPasswordRequest.
type DeleteAppPasswordRequest struct {
	AppPassword string `json:"appPassword"`
	UserName    string `json:"userName"`
}

// DeleteDomainRequest defines model for DeleteDomainRequest.
type DeleteDomainRequest struct {
	Name string `json:"name"`
}

// DeletePasswordResetRequest defines model for DeletePasswordResetRequest.
type DeletePasswordResetRequest struct {
	Target   string `json:"target"`
	UserName string `json:"userName"`
}

// DeleteRoutingRequest defines model for DeleteRoutingRequest.
type DeleteRoutingRequest struct {
	RoutingRuleId int32 `json:"routingRuleId"`
}

// DeleteUserRequest defines model for DeleteUserRequest.
type DeleteUserRequest struct {
	UserName string `json:"userName"`
}

// EmptyRequest defines model for EmptyRequest.
type EmptyRequest = map[string]interface{}

// EmptyResponse defines model for EmptyResponse.
type EmptyResponse struct {
	Result *map[string]interface{} `json:"result,omitempty"`
}

// GetOwnershipCodeResponse defines model for GetOwnershipCodeResponse.
type GetOwnershipCodeResponse struct {
	Result *struct {
		Code *string `json:"code,omitempty"`
	} `json:"result,omitempty"`
}

// GetUserPasswordResetMethod defines model for GetUserPasswordResetMethod.
type GetUserPasswordResetMethod struct {
	AllowMfaReset *bool                        `json:"allowMfaReset,omitempty"`
	Description   *string                      `json:"description,omitempty"`
	Target        *string                      `json:"target,omitempty"`
	Type          *UserPasswordResetMethodType `json:"type,omitempty"`
}

// GetUserRequest defines model for GetUserRequest.
type GetUserRequest struct {
	UserName string `json:"userName"`
}

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	Result *struct {
		EnableSearchIndexing           *bool                         `json:"enableSearchIndexing,omitempty"`
		EnableSpamFiltering            *bool                         `json:"enableSpamFiltering,omitempty"`
		RecoveryEnabled                *bool                         `json:"recoveryEnabled,omitempty"`
		RequireTwoFactorAuthentication *bool                         `json:"requireTwoFactorAuthentication,omitempty"`
		ResetMethods                   *[]GetUserPasswordResetMethod `json:"resetMethods,omitempty"`
	} `json:"result,omitempty"`
}

// ListDomainsRequest defines model for ListDomainsRequest.
type ListDomainsRequest struct {
	IncludeShared *bool `json:"includeShared,omitempty"`
}

// ListDomainsResponse defines model for ListDomainsResponse.
type ListDomainsResponse struct {
	Result *struct {
		Domains *[]ApiDomainInfo `json:"domains,omitempty"`
	} `json:"result,omitempty"`
}

// ListPasswordResetRequest defines model for ListPasswordResetRequest.
type ListPasswordResetRequest struct {
	UserName string `json:"userName"`
}

// ListPasswordResetResponse defines model for ListPasswordResetResponse.
type ListPasswordResetResponse struct {
	Result *struct {
		Users *[]ListPasswordResetResponseItem `json:"users,omitempty"`
	} `json:"result,omitempty"`
}

// ListPasswordResetResponseItem defines model for ListPasswordResetResponseItem.
type ListPasswordResetResponseItem struct {
	AllowMfaReset *bool   `json:"allowMfaReset,omitempty"`
	Description   *string `json:"description,omitempty"`
	Target        *string `json:"target,omitempty"`
	Type          *string `json:"type,omitempty"`
}

// ListRoutingResponse defines model for ListRoutingResponse.
type ListRoutingResponse struct {
	Result *struct {
		Rules *[]RoutingRule `json:"rules,omitempty"`
	} `json:"result,omitempty"`
}

// ListUserResponse defines model for ListUserResponse.
type ListUserResponse struct {
	Result *struct {
		Users *[]string `json:"users,omitempty"`
	} `json:"result,omitempty"`
}

// ModifyUserRequest defines model for ModifyUserRequest.
type ModifyUserRequest struct {
	EnablePasswordReset            *bool   `json:"enablePasswordReset,omitempty"`
	EnableSearchIndexing           *bool   `json:"enableSearchIndexing,omitempty"`
	NewPassword                    *string `json:"newPassword,omitempty"`
	NewUserName                    *string `json:"newUserName,omitempty"`
	RequireTwoFactorAuthentication *bool   `json:"requireTwoFactorAuthentication,omitempty"`
	UserName                       string  `json:"userName"`
}

// RoutingRule defines model for RoutingRule.
type RoutingRule struct {
	Catchall        *bool     `json:"catchall,omitempty"`
	DomainName      *string   `json:"domainName,omitempty"`
	Id              *int32    `json:"id,omitempty"`
	MatchUser       *string   `json:"matchUser,omitempty"`
	Prefix          *bool     `json:"prefix,omitempty"`
	TargetAddresses *[]string `json:"targetAddresses,omitempty"`
}

// UpdateDomainSettingsRequest defines model for UpdateDomainSettingsRequest.
type UpdateDomainSettingsRequest struct {
	AllowAccountReset     *bool  `json:"allowAccountReset,omitempty"`
	Name                  string `json:"name"`
	RecheckDns            *bool  `json:"recheckDns,omitempty"`
	SymbolicSubaddressing *bool  `json:"symbolicSubaddressing,omitempty"`
}

// UpsertPasswordResetRequest defines model for UpsertPasswordResetRequest.
type UpsertPasswordResetRequest struct {
	AllowMfaReset  *bool   `json:"allowMfaReset,omitempty"`
	Description    *string `json:"description,omitempty"`
	ExistingTarget *string `json:"existingTarget,omitempty"`
	Target         string  `json:"target"`
	Type           string  `json:"type"`
	UserName       string  `json:"userName"`
}

// UserPasswordResetMethodType defines model for UserPasswordResetMethodType.
type UserPasswordResetMethodType = map[string]interface{}

// AddDomainJSONRequestBody defines body for AddDomain for application/json ContentType.
type AddDomainJSONRequestBody = AddDomainRequest

// CheckAccountCreditJSONRequestBody defines body for CheckAccountCredit for application/json ContentType.
type CheckAccountCreditJSONRequestBody = EmptyRequest

// CreateAppPasswordJSONRequestBody defines body for CreateAppPassword for application/json ContentType.
type CreateAppPasswordJSONRequestBody = CreateAppPassword

// CreateRoutingRuleJSONRequestBody defines body for CreateRoutingRule for application/json ContentType.
type CreateRoutingRuleJSONRequestBody = CreateRoutingRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// DeleteAppPasswordJSONRequestBody defines body for DeleteAppPassword for application/json ContentType.
type DeleteAppPasswordJSONRequestBody = DeleteAppPasswordRequest

// DeleteDomainJSONRequestBody defines body for DeleteDomain for application/json ContentType.
type DeleteDomainJSONRequestBody = DeleteDomainRequest

// DeletePasswordResetMethodJSONRequestBody defines body for DeletePasswordResetMethod for application/json ContentType.
type DeletePasswordResetMethodJSONRequestBody = DeletePasswordResetRequest

// DeleteRoutingRuleJSONRequestBody defines body for DeleteRoutingRule for application/json ContentType.
type DeleteRoutingRuleJSONRequestBody = DeleteRoutingRequest

// DeleteUserJSONRequestBody defines body for DeleteUser for application/json ContentType.
type DeleteUserJSONRequestBody = DeleteUserRequest

// GetOwnershipCodeJSONRequestBody defines body for GetOwnershipCode for application/json ContentType.
type GetOwnershipCodeJSONRequestBody = EmptyRequest

// GetUserJSONRequestBody defines body for GetUser for application/json ContentType.
type GetUserJSONRequestBody = GetUserRequest

// ListDomainsJSONRequestBody defines body for ListDomains for application/json ContentType.
type ListDomainsJSONRequestBody = ListDomainsRequest

// ListPasswordResetMethodsJSONRequestBody defines body for ListPasswordResetMethods for application/json ContentType.
type ListPasswordResetMethodsJSONRequestBody = ListPasswordResetRequest

// ListRoutingRulesJSONRequestBody defines body for ListRoutingRules for application/json ContentType.
type ListRoutingRulesJSONRequestBody = EmptyRequest

// ListUsersJSONRequestBody defines body for ListUsers for application/json ContentType.
type ListUsersJSONRequestBody = EmptyRequest

// ModifyUserJSONRequestBody defines body for ModifyUser for application/json ContentType.
type ModifyUserJSONRequestBody = ModifyUserRequest

// UpdateDomainSettingsJSONRequestBody defines body for UpdateDomainSettings for application/json ContentType.
type UpdateDomainSettingsJSONRequestBody = UpdateDomainSettingsRequest

// CreateOrUpdatePasswordResetMethodJSONRequestBody defines body for CreateOrUpdatePasswordResetMethod for application/json ContentType.
type CreateOrUpdatePasswordResetMethodJSONRequestBody = UpsertPasswordResetRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AddDomainWithBody request with any body
	AddDomainWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddDomain(ctx context.Context, body AddDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CheckAccountCreditWithBody request with any body
	CheckAccountCreditWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CheckAccountCredit(ctx context.Context, body CheckAccountCreditJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAppPasswordWithBody request with any body
	CreateAppPasswordWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAppPassword(ctx context.Context, body CreateAppPasswordJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRoutingRuleWithBody request with any body
	CreateRoutingRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRoutingRule(ctx context.Context, body CreateRoutingRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUserWithBody request with any body
	CreateUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUser(ctx context.Context, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAppPasswordWithBody request with any body
	DeleteAppPasswordWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteAppPassword(ctx context.Context, body DeleteAppPasswordJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDomainWithBody request with any body
	DeleteDomainWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteDomain(ctx context.Context, body DeleteDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeletePasswordResetMethodWithBody request with any body
	DeletePasswordResetMethodWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeletePasswordResetMethod(ctx context.Context, body DeletePasswordResetMethodJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteRoutingRuleWithBody request with any body
	DeleteRoutingRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteRoutingRule(ctx context.Context, body DeleteRoutingRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUserWithBody request with any body
	DeleteUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteUser(ctx context.Context, body DeleteUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetOwnershipCodeWithBody request with any body
	GetOwnershipCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetOwnershipCode(ctx context.Context, body GetOwnershipCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserWithBody request with any body
	GetUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetUser(ctx context.Context, body GetUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDomainsWithBody request with any body
	ListDomainsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListDomains(ctx context.Context, body ListDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPasswordResetMethodsWithBody request with any body
	ListPasswordResetMethodsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListPasswordResetMethods(ctx context.Context, body ListPasswordResetMethodsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListRoutingRulesWithBody request with any body
	ListRoutingRulesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListRoutingRules(ctx context.Context, body ListRoutingRulesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListUsersWithBody request with any body
	ListUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListUsers(ctx context.Context, body ListUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ModifyUserWithBody request with any body
	ModifyUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ModifyUser(ctx context.Context, body ModifyUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDomainSettingsWithBody request with any body
	UpdateDomainSettingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateDomainSettings(ctx context.Context, body UpdateDomainSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOrUpdatePasswordResetMethodWithBody request with any body
	CreateOrUpdatePasswordResetMethodWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateOrUpdatePasswordResetMethod(ctx context.Context, body CreateOrUpdatePasswordResetMethodJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AddDomainWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddDomainRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddDomain(ctx context.Context, body AddDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddDomainRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckAccountCreditWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckAccountCreditRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CheckAccountCredit(ctx context.Context, body CheckAccountCreditJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCheckAccountCreditRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAppPasswordWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAppPasswordRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAppPassword(ctx context.Context, body CreateAppPasswordJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAppPasswordRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRoutingRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRoutingRuleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRoutingRule(ctx context.Context, body CreateRoutingRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRoutingRuleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUser(ctx context.Context, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAppPasswordWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAppPasswordRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAppPassword(ctx context.Context, body DeleteAppPasswordJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAppPasswordRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteDomainWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDomainRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteDomain(ctx context.Context, body DeleteDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDomainRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeletePasswordResetMethodWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePasswordResetMethodRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeletePasswordResetMethod(ctx context.Context, body DeletePasswordResetMethodJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePasswordResetMethodRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteRoutingRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteRoutingRuleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteRoutingRule(ctx context.Context, body DeleteRoutingRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteRoutingRuleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUser(ctx context.Context, body DeleteUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOwnershipCodeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOwnershipCodeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetOwnershipCode(ctx context.Context, body GetOwnershipCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOwnershipCodeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUser(ctx context.Context, body GetUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDomainsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDomainsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDomains(ctx context.Context, body ListDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDomainsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPasswordResetMethodsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPasswordResetMethodsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPasswordResetMethods(ctx context.Context, body ListPasswordResetMethodsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPasswordResetMethodsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListRoutingRulesWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListRoutingRulesRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListRoutingRules(ctx context.Context, body ListRoutingRulesJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListRoutingRulesRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListUsersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListUsersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListUsers(ctx context.Context, body ListUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListUsersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ModifyUserWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewModifyUserRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ModifyUser(ctx context.Context, body ModifyUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewModifyUserRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDomainSettingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDomainSettingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDomainSettings(ctx context.Context, body UpdateDomainSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDomainSettingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOrUpdatePasswordResetMethodWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrUpdatePasswordResetMethodRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOrUpdatePasswordResetMethod(ctx context.Context, body CreateOrUpdatePasswordResetMethodJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOrUpdatePasswordResetMethodRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAddDomainRequest calls the generic AddDomain builder with application/json body
func NewAddDomainRequest(server string, body AddDomainJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddDomainRequestWithBody(server, "application/json", bodyReader)
}

// NewAddDomainRequestWithBody generates requests for AddDomain with any type of body
func NewAddDomainRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/addDomain")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCheckAccountCreditRequest calls the generic CheckAccountCredit builder with application/json body
func NewCheckAccountCreditRequest(server string, body CheckAccountCreditJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCheckAccountCreditRequestWithBody(server, "application/json", bodyReader)
}

// NewCheckAccountCreditRequestWithBody generates requests for CheckAccountCredit with any type of body
func NewCheckAccountCreditRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/checkAccountCredit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateAppPasswordRequest calls the generic CreateAppPassword builder with application/json body
func NewCreateAppPasswordRequest(server string, body CreateAppPasswordJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAppPasswordRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAppPasswordRequestWithBody generates requests for CreateAppPassword with any type of body
func NewCreateAppPasswordRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/createAppPassword")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateRoutingRuleRequest calls the generic CreateRoutingRule builder with application/json body
func NewCreateRoutingRuleRequest(server string, body CreateRoutingRuleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRoutingRuleRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateRoutingRuleRequestWithBody generates requests for CreateRoutingRule with any type of body
func NewCreateRoutingRuleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/createRoutingRule")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateUserRequest calls the generic CreateUser builder with application/json body
func NewCreateUserRequest(server string, body CreateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUserRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateUserRequestWithBody generates requests for CreateUser with any type of body
func NewCreateUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/createUser")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAppPasswordRequest calls the generic DeleteAppPassword builder with application/json body
func NewDeleteAppPasswordRequest(server string, body DeleteAppPasswordJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteAppPasswordRequestWithBody(server, "application/json", bodyReader)
}

// NewDeleteAppPasswordRequestWithBody generates requests for DeleteAppPassword with any type of body
func NewDeleteAppPasswordRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/deleteAppPassword")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDomainRequest calls the generic DeleteDomain builder with application/json body
func NewDeleteDomainRequest(server string, body DeleteDomainJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteDomainRequestWithBody(server, "application/json", bodyReader)
}

// NewDeleteDomainRequestWithBody generates requests for DeleteDomain with any type of body
func NewDeleteDomainRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/deleteDomain")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeletePasswordResetMethodRequest calls the generic DeletePasswordResetMethod builder with application/json body
func NewDeletePasswordResetMethodRequest(server string, body DeletePasswordResetMethodJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeletePasswordResetMethodRequestWithBody(server, "application/json", bodyReader)
}

// NewDeletePasswordResetMethodRequestWithBody generates requests for DeletePasswordResetMethod with any type of body
func NewDeletePasswordResetMethodRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/deletePasswordReset")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteRoutingRuleRequest calls the generic DeleteRoutingRule builder with application/json body
func NewDeleteRoutingRuleRequest(server string, body DeleteRoutingRuleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteRoutingRuleRequestWithBody(server, "application/json", bodyReader)
}

// NewDeleteRoutingRuleRequestWithBody generates requests for DeleteRoutingRule with any type of body
func NewDeleteRoutingRuleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/deleteRoutingRule")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteUserRequest calls the generic DeleteUser builder with application/json body
func NewDeleteUserRequest(server string, body DeleteUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteUserRequestWithBody(server, "application/json", bodyReader)
}

// NewDeleteUserRequestWithBody generates requests for DeleteUser with any type of body
func NewDeleteUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/deleteUser")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetOwnershipCodeRequest calls the generic GetOwnershipCode builder with application/json body
func NewGetOwnershipCodeRequest(server string, body GetOwnershipCodeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetOwnershipCodeRequestWithBody(server, "application/json", bodyReader)
}

// NewGetOwnershipCodeRequestWithBody generates requests for GetOwnershipCode with any type of body
func NewGetOwnershipCodeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/getOwnershipCode")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetUserRequest calls the generic GetUser builder with application/json body
func NewGetUserRequest(server string, body GetUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetUserRequestWithBody(server, "application/json", bodyReader)
}

// NewGetUserRequestWithBody generates requests for GetUser with any type of body
func NewGetUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/getUser")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListDomainsRequest calls the generic ListDomains builder with application/json body
func NewListDomainsRequest(server string, body ListDomainsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListDomainsRequestWithBody(server, "application/json", bodyReader)
}

// NewListDomainsRequestWithBody generates requests for ListDomains with any type of body
func NewListDomainsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/listDomains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListPasswordResetMethodsRequest calls the generic ListPasswordResetMethods builder with application/json body
func NewListPasswordResetMethodsRequest(server string, body ListPasswordResetMethodsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListPasswordResetMethodsRequestWithBody(server, "application/json", bodyReader)
}

// NewListPasswordResetMethodsRequestWithBody generates requests for ListPasswordResetMethods with any type of body
func NewListPasswordResetMethodsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/listPasswordReset")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListRoutingRulesRequest calls the generic ListRoutingRules builder with application/json body
func NewListRoutingRulesRequest(server string, body ListRoutingRulesJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListRoutingRulesRequestWithBody(server, "application/json", bodyReader)
}

// NewListRoutingRulesRequestWithBody generates requests for ListRoutingRules with any type of body
func NewListRoutingRulesRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/listRoutingRules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListUsersRequest calls the generic ListUsers builder with application/json body
func NewListUsersRequest(server string, body ListUsersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListUsersRequestWithBody(server, "application/json", bodyReader)
}

// NewListUsersRequestWithBody generates requests for ListUsers with any type of body
func NewListUsersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/listUser")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewModifyUserRequest calls the generic ModifyUser builder with application/json body
func NewModifyUserRequest(server string, body ModifyUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewModifyUserRequestWithBody(server, "application/json", bodyReader)
}

// NewModifyUserRequestWithBody generates requests for ModifyUser with any type of body
func NewModifyUserRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/modifyUser")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateDomainSettingsRequest calls the generic UpdateDomainSettings builder with application/json body
func NewUpdateDomainSettingsRequest(server string, body UpdateDomainSettingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDomainSettingsRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateDomainSettingsRequestWithBody generates requests for UpdateDomainSettings with any type of body
func NewUpdateDomainSettingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/updateDomainSettings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateOrUpdatePasswordResetMethodRequest calls the generic CreateOrUpdatePasswordResetMethod builder with application/json body
func NewCreateOrUpdatePasswordResetMethodRequest(server string, body CreateOrUpdatePasswordResetMethodJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOrUpdatePasswordResetMethodRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateOrUpdatePasswordResetMethodRequestWithBody generates requests for CreateOrUpdatePasswordResetMethod with any type of body
func NewCreateOrUpdatePasswordResetMethodRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v0/upsertPasswordReset")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AddDomainWithBodyWithResponse request with any body
	AddDomainWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddDomainResp, error)

	AddDomainWithResponse(ctx context.Context, body AddDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*AddDomainResp, error)

	// CheckAccountCreditWithBodyWithResponse request with any body
	CheckAccountCreditWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckAccountCreditResp, error)

	CheckAccountCreditWithResponse(ctx context.Context, body CheckAccountCreditJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckAccountCreditResp, error)

	// CreateAppPasswordWithBodyWithResponse request with any body
	CreateAppPasswordWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAppPasswordResp, error)

	CreateAppPasswordWithResponse(ctx context.Context, body CreateAppPasswordJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAppPasswordResp, error)

	// CreateRoutingRuleWithBodyWithResponse request with any body
	CreateRoutingRuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRoutingRuleResp, error)

	CreateRoutingRuleWithResponse(ctx context.Context, body CreateRoutingRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRoutingRuleResp, error)

	// CreateUserWithBodyWithResponse request with any body
	CreateUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserResp, error)

	CreateUserWithResponse(ctx context.Context, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserResp, error)

	// DeleteAppPasswordWithBodyWithResponse request with any body
	DeleteAppPasswordWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteAppPasswordResp, error)

	DeleteAppPasswordWithResponse(ctx context.Context, body DeleteAppPasswordJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteAppPasswordResp, error)

	// DeleteDomainWithBodyWithResponse request with any body
	DeleteDomainWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteDomainResp, error)

	DeleteDomainWithResponse(ctx context.Context, body DeleteDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteDomainResp, error)

	// DeletePasswordResetMethodWithBodyWithResponse request with any body
	DeletePasswordResetMethodWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeletePasswordResetMethodResp, error)

	DeletePasswordResetMethodWithResponse(ctx context.Context, body DeletePasswordResetMethodJSONRequestBody, reqEditors ...RequestEditorFn) (*DeletePasswordResetMethodResp, error)

	// DeleteRoutingRuleWithBodyWithResponse request with any body
	DeleteRoutingRuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteRoutingRuleResp, error)

	DeleteRoutingRuleWithResponse(ctx context.Context, body DeleteRoutingRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteRoutingRuleResp, error)

	// DeleteUserWithBodyWithResponse request with any body
	DeleteUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteUserResp, error)

	DeleteUserWithResponse(ctx context.Context, body DeleteUserJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteUserResp, error)

	// GetOwnershipCodeWithBodyWithResponse request with any body
	GetOwnershipCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetOwnershipCodeResp, error)

	GetOwnershipCodeWithResponse(ctx context.Context, body GetOwnershipCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*GetOwnershipCodeResp, error)

	// GetUserWithBodyWithResponse request with any body
	GetUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetUserResp, error)

	GetUserWithResponse(ctx context.Context, body GetUserJSONRequestBody, reqEditors ...RequestEditorFn) (*GetUserResp, error)

	// ListDomainsWithBodyWithResponse request with any body
	ListDomainsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListDomainsResp, error)

	ListDomainsWithResponse(ctx context.Context, body ListDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListDomainsResp, error)

	// ListPasswordResetMethodsWithBodyWithResponse request with any body
	ListPasswordResetMethodsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListPasswordResetMethodsResp, error)

	ListPasswordResetMethodsWithResponse(ctx context.Context, body ListPasswordResetMethodsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListPasswordResetMethodsResp, error)

	// ListRoutingRulesWithBodyWithResponse request with any body
	ListRoutingRulesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListRoutingRulesResp, error)

	ListRoutingRulesWithResponse(ctx context.Context, body ListRoutingRulesJSONRequestBody, reqEditors ...RequestEditorFn) (*ListRoutingRulesResp, error)

	// ListUsersWithBodyWithResponse request with any body
	ListUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListUsersResp, error)

	ListUsersWithResponse(ctx context.Context, body ListUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*ListUsersResp, error)

	// ModifyUserWithBodyWithResponse request with any body
	ModifyUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ModifyUserResp, error)

	ModifyUserWithResponse(ctx context.Context, body ModifyUserJSONRequestBody, reqEditors ...RequestEditorFn) (*ModifyUserResp, error)

	// UpdateDomainSettingsWithBodyWithResponse request with any body
	UpdateDomainSettingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDomainSettingsResp, error)

	UpdateDomainSettingsWithResponse(ctx context.Context, body UpdateDomainSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDomainSettingsResp, error)

	// CreateOrUpdatePasswordResetMethodWithBodyWithResponse request with any body
	CreateOrUpdatePasswordResetMethodWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrUpdatePasswordResetMethodResp, error)

	CreateOrUpdatePasswordResetMethodWithResponse(ctx context.Context, body CreateOrUpdatePasswordResetMethodJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrUpdatePasswordResetMethodResp, error)
}

type AddDomainResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r AddDomainResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddDomainResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CheckAccountCreditResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CheckCreditResponse
}

// Status returns HTTPResponse.Status
func (r CheckAccountCreditResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CheckAccountCreditResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateAppPasswordResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateAppPasswordResponse
}

// Status returns HTTPResponse.Status
func (r CreateAppPasswordResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAppPasswordResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateRoutingRuleResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r CreateRoutingRuleResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRoutingRuleResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUserResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r CreateUserResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUserResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAppPasswordResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAppPasswordResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAppPasswordResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteDomainResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r DeleteDomainResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDomainResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeletePasswordResetMethodResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r DeletePasswordResetMethodResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeletePasswordResetMethodResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteRoutingRuleResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r DeleteRoutingRuleResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteRoutingRuleResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUserResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r DeleteUserResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetOwnershipCodeResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetOwnershipCodeResponse
}

// Status returns HTTPResponse.Status
func (r GetOwnershipCodeResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOwnershipCodeResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetUserResponse
}

// Status returns HTTPResponse.Status
func (r GetUserResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListDomainsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListDomainsResponse
}

// Status returns HTTPResponse.Status
func (r ListDomainsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDomainsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListPasswordResetMethodsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListPasswordResetResponse
}

// Status returns HTTPResponse.Status
func (r ListPasswordResetMethodsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPasswordResetMethodsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListRoutingRulesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListRoutingResponse
}

// Status returns HTTPResponse.Status
func (r ListRoutingRulesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListRoutingRulesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListUsersResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListUserResponse
}

// Status returns HTTPResponse.Status
func (r ListUsersResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListUsersResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ModifyUserResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r ModifyUserResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ModifyUserResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateDomainSettingsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r UpdateDomainSettingsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDomainSettingsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateOrUpdatePasswordResetMethodResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EmptyResponse
}

// Status returns HTTPResponse.Status
func (r CreateOrUpdatePasswordResetMethodResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOrUpdatePasswordResetMethodResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AddDomainWithBodyWithResponse request with arbitrary body returning *AddDomainResp
func (c *ClientWithResponses) AddDomainWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddDomainResp, error) {
	rsp, err := c.AddDomainWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddDomainResp(rsp)
}

func (c *ClientWithResponses) AddDomainWithResponse(ctx context.Context, body AddDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*AddDomainResp, error) {
	rsp, err := c.AddDomain(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddDomainResp(rsp)
}

// CheckAccountCreditWithBodyWithResponse request with arbitrary body returning *CheckAccountCreditResp
func (c *ClientWithResponses) CheckAccountCreditWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CheckAccountCreditResp, error) {
	rsp, err := c.CheckAccountCreditWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckAccountCreditResp(rsp)
}

func (c *ClientWithResponses) CheckAccountCreditWithResponse(ctx context.Context, body CheckAccountCreditJSONRequestBody, reqEditors ...RequestEditorFn) (*CheckAccountCreditResp, error) {
	rsp, err := c.CheckAccountCredit(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCheckAccountCreditResp(rsp)
}

// CreateAppPasswordWithBodyWithResponse request with arbitrary body returning *CreateAppPasswordResp
func (c *ClientWithResponses) CreateAppPasswordWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAppPasswordResp, error) {
	rsp, err := c.CreateAppPasswordWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAppPasswordResp(rsp)
}

func (c *ClientWithResponses) CreateAppPasswordWithResponse(ctx context.Context, body CreateAppPasswordJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAppPasswordResp, error) {
	rsp, err := c.CreateAppPassword(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAppPasswordResp(rsp)
}

// CreateRoutingRuleWithBodyWithResponse request with arbitrary body returning *CreateRoutingRuleResp
func (c *ClientWithResponses) CreateRoutingRuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRoutingRuleResp, error) {
	rsp, err := c.CreateRoutingRuleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRoutingRuleResp(rsp)
}

func (c *ClientWithResponses) CreateRoutingRuleWithResponse(ctx context.Context, body CreateRoutingRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRoutingRuleResp, error) {
	rsp, err := c.CreateRoutingRule(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRoutingRuleResp(rsp)
}

// CreateUserWithBodyWithResponse request with arbitrary body returning *CreateUserResp
func (c *ClientWithResponses) CreateUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserResp, error) {
	rsp, err := c.CreateUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserResp(rsp)
}

func (c *ClientWithResponses) CreateUserWithResponse(ctx context.Context, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserResp, error) {
	rsp, err := c.CreateUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserResp(rsp)
}

// DeleteAppPasswordWithBodyWithResponse request with arbitrary body returning *DeleteAppPasswordResp
func (c *ClientWithResponses) DeleteAppPasswordWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteAppPasswordResp, error) {
	rsp, err := c.DeleteAppPasswordWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAppPasswordResp(rsp)
}

func (c *ClientWithResponses) DeleteAppPasswordWithResponse(ctx context.Context, body DeleteAppPasswordJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteAppPasswordResp, error) {
	rsp, err := c.DeleteAppPassword(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAppPasswordResp(rsp)
}

// DeleteDomainWithBodyWithResponse request with arbitrary body returning *DeleteDomainResp
func (c *ClientWithResponses) DeleteDomainWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteDomainResp, error) {
	rsp, err := c.DeleteDomainWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDomainResp(rsp)
}

func (c *ClientWithResponses) DeleteDomainWithResponse(ctx context.Context, body DeleteDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteDomainResp, error) {
	rsp, err := c.DeleteDomain(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDomainResp(rsp)
}

// DeletePasswordResetMethodWithBodyWithResponse request with arbitrary body returning *DeletePasswordResetMethodResp
func (c *ClientWithResponses) DeletePasswordResetMethodWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeletePasswordResetMethodResp, error) {
	rsp, err := c.DeletePasswordResetMethodWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePasswordResetMethodResp(rsp)
}

func (c *ClientWithResponses) DeletePasswordResetMethodWithResponse(ctx context.Context, body DeletePasswordResetMethodJSONRequestBody, reqEditors ...RequestEditorFn) (*DeletePasswordResetMethodResp, error) {
	rsp, err := c.DeletePasswordResetMethod(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePasswordResetMethodResp(rsp)
}

// DeleteRoutingRuleWithBodyWithResponse request with arbitrary body returning *DeleteRoutingRuleResp
func (c *ClientWithResponses) DeleteRoutingRuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteRoutingRuleResp, error) {
	rsp, err := c.DeleteRoutingRuleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteRoutingRuleResp(rsp)
}

func (c *ClientWithResponses) DeleteRoutingRuleWithResponse(ctx context.Context, body DeleteRoutingRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteRoutingRuleResp, error) {
	rsp, err := c.DeleteRoutingRule(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteRoutingRuleResp(rsp)
}

// DeleteUserWithBodyWithResponse request with arbitrary body returning *DeleteUserResp
func (c *ClientWithResponses) DeleteUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteUserResp, error) {
	rsp, err := c.DeleteUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserResp(rsp)
}

func (c *ClientWithResponses) DeleteUserWithResponse(ctx context.Context, body DeleteUserJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteUserResp, error) {
	rsp, err := c.DeleteUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserResp(rsp)
}

// GetOwnershipCodeWithBodyWithResponse request with arbitrary body returning *GetOwnershipCodeResp
func (c *ClientWithResponses) GetOwnershipCodeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetOwnershipCodeResp, error) {
	rsp, err := c.GetOwnershipCodeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOwnershipCodeResp(rsp)
}

func (c *ClientWithResponses) GetOwnershipCodeWithResponse(ctx context.Context, body GetOwnershipCodeJSONRequestBody, reqEditors ...RequestEditorFn) (*GetOwnershipCodeResp, error) {
	rsp, err := c.GetOwnershipCode(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOwnershipCodeResp(rsp)
}

// GetUserWithBodyWithResponse request with arbitrary body returning *GetUserResp
func (c *ClientWithResponses) GetUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetUserResp, error) {
	rsp, err := c.GetUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResp(rsp)
}

func (c *ClientWithResponses) GetUserWithResponse(ctx context.Context, body GetUserJSONRequestBody, reqEditors ...RequestEditorFn) (*GetUserResp, error) {
	rsp, err := c.GetUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResp(rsp)
}

// ListDomainsWithBodyWithResponse request with arbitrary body returning *ListDomainsResp
func (c *ClientWithResponses) ListDomainsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListDomainsResp, error) {
	rsp, err := c.ListDomainsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDomainsResp(rsp)
}

func (c *ClientWithResponses) ListDomainsWithResponse(ctx context.Context, body ListDomainsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListDomainsResp, error) {
	rsp, err := c.ListDomains(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDomainsResp(rsp)
}

// ListPasswordResetMethodsWithBodyWithResponse request with arbitrary body returning *ListPasswordResetMethodsResp
func (c *ClientWithResponses) ListPasswordResetMethodsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListPasswordResetMethodsResp, error) {
	rsp, err := c.ListPasswordResetMethodsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPasswordResetMethodsResp(rsp)
}

func (c *ClientWithResponses) ListPasswordResetMethodsWithResponse(ctx context.Context, body ListPasswordResetMethodsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListPasswordResetMethodsResp, error) {
	rsp, err := c.ListPasswordResetMethods(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPasswordResetMethodsResp(rsp)
}

// ListRoutingRulesWithBodyWithResponse request with arbitrary body returning *ListRoutingRulesResp
func (c *ClientWithResponses) ListRoutingRulesWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListRoutingRulesResp, error) {
	rsp, err := c.ListRoutingRulesWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListRoutingRulesResp(rsp)
}

func (c *ClientWithResponses) ListRoutingRulesWithResponse(ctx context.Context, body ListRoutingRulesJSONRequestBody, reqEditors ...RequestEditorFn) (*ListRoutingRulesResp, error) {
	rsp, err := c.ListRoutingRules(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListRoutingRulesResp(rsp)
}

// ListUsersWithBodyWithResponse request with arbitrary body returning *ListUsersResp
func (c *ClientWithResponses) ListUsersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListUsersResp, error) {
	rsp, err := c.ListUsersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListUsersResp(rsp)
}

func (c *ClientWithResponses) ListUsersWithResponse(ctx context.Context, body ListUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*ListUsersResp, error) {
	rsp, err := c.ListUsers(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListUsersResp(rsp)
}

// ModifyUserWithBodyWithResponse request with arbitrary body returning *ModifyUserResp
func (c *ClientWithResponses) ModifyUserWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ModifyUserResp, error) {
	rsp, err := c.ModifyUserWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseModifyUserResp(rsp)
}

func (c *ClientWithResponses) ModifyUserWithResponse(ctx context.Context, body ModifyUserJSONRequestBody, reqEditors ...RequestEditorFn) (*ModifyUserResp, error) {
	rsp, err := c.ModifyUser(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseModifyUserResp(rsp)
}

// UpdateDomainSettingsWithBodyWithResponse request with arbitrary body returning *UpdateDomainSettingsResp
func (c *ClientWithResponses) UpdateDomainSettingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDomainSettingsResp, error) {
	rsp, err := c.UpdateDomainSettingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDomainSettingsResp(rsp)
}

func (c *ClientWithResponses) UpdateDomainSettingsWithResponse(ctx context.Context, body UpdateDomainSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDomainSettingsResp, error) {
	rsp, err := c.UpdateDomainSettings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDomainSettingsResp(rsp)
}

// CreateOrUpdatePasswordResetMethodWithBodyWithResponse request with arbitrary body returning *CreateOrUpdatePasswordResetMethodResp
func (c *ClientWithResponses) CreateOrUpdatePasswordResetMethodWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrUpdatePasswordResetMethodResp, error) {
	rsp, err := c.CreateOrUpdatePasswordResetMethodWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOrUpdatePasswordResetMethodResp(rsp)
}

func (c *ClientWithResponses) CreateOrUpdatePasswordResetMethodWithResponse(ctx context.Context, body CreateOrUpdatePasswordResetMethodJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrUpdatePasswordResetMethodResp, error) {
	rsp, err := c.CreateOrUpdatePasswordResetMethod(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOrUpdatePasswordResetMethodResp(rsp)
}

// ParseAddDomainResp parses an HTTP response from a AddDomainWithResponse call
func ParseAddDomainResp(rsp *http.Response) (*AddDomainResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddDomainResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCheckAccountCreditResp parses an HTTP response from a CheckAccountCreditWithResponse call
func ParseCheckAccountCreditResp(rsp *http.Response) (*CheckAccountCreditResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CheckAccountCreditResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CheckCreditResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateAppPasswordResp parses an HTTP response from a CreateAppPasswordWithResponse call
func ParseCreateAppPasswordResp(rsp *http.Response) (*CreateAppPasswordResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAppPasswordResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateAppPasswordResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateRoutingRuleResp parses an HTTP response from a CreateRoutingRuleWithResponse call
func ParseCreateRoutingRuleResp(rsp *http.Response) (*CreateRoutingRuleResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRoutingRuleResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateUserResp parses an HTTP response from a CreateUserWithResponse call
func ParseCreateUserResp(rsp *http.Response) (*CreateUserResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUserResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteAppPasswordResp parses an HTTP response from a DeleteAppPasswordWithResponse call
func ParseDeleteAppPasswordResp(rsp *http.Response) (*DeleteAppPasswordResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAppPasswordResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteDomainResp parses an HTTP response from a DeleteDomainWithResponse call
func ParseDeleteDomainResp(rsp *http.Response) (*DeleteDomainResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDomainResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeletePasswordResetMethodResp parses an HTTP response from a DeletePasswordResetMethodWithResponse call
func ParseDeletePasswordResetMethodResp(rsp *http.Response) (*DeletePasswordResetMethodResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeletePasswordResetMethodResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteRoutingRuleResp parses an HTTP response from a DeleteRoutingRuleWithResponse call
func ParseDeleteRoutingRuleResp(rsp *http.Response) (*DeleteRoutingRuleResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteRoutingRuleResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteUserResp parses an HTTP response from a DeleteUserWithResponse call
func ParseDeleteUserResp(rsp *http.Response) (*DeleteUserResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetOwnershipCodeResp parses an HTTP response from a GetOwnershipCodeWithResponse call
func ParseGetOwnershipCodeResp(rsp *http.Response) (*GetOwnershipCodeResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOwnershipCodeResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetOwnershipCodeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetUserResp parses an HTTP response from a GetUserWithResponse call
func ParseGetUserResp(rsp *http.Response) (*GetUserResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetUserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListDomainsResp parses an HTTP response from a ListDomainsWithResponse call
func ParseListDomainsResp(rsp *http.Response) (*ListDomainsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDomainsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListDomainsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListPasswordResetMethodsResp parses an HTTP response from a ListPasswordResetMethodsWithResponse call
func ParseListPasswordResetMethodsResp(rsp *http.Response) (*ListPasswordResetMethodsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPasswordResetMethodsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListPasswordResetResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListRoutingRulesResp parses an HTTP response from a ListRoutingRulesWithResponse call
func ParseListRoutingRulesResp(rsp *http.Response) (*ListRoutingRulesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListRoutingRulesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListRoutingResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListUsersResp parses an HTTP response from a ListUsersWithResponse call
func ParseListUsersResp(rsp *http.Response) (*ListUsersResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListUsersResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListUserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseModifyUserResp parses an HTTP response from a ModifyUserWithResponse call
func ParseModifyUserResp(rsp *http.Response) (*ModifyUserResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ModifyUserResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateDomainSettingsResp parses an HTTP response from a UpdateDomainSettingsWithResponse call
func ParseUpdateDomainSettingsResp(rsp *http.Response) (*UpdateDomainSettingsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDomainSettingsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateOrUpdatePasswordResetMethodResp parses an HTTP response from a CreateOrUpdatePasswordResetMethodWithResponse call
func ParseCreateOrUpdatePasswordResetMethodResp(rsp *http.Response) (*CreateOrUpdatePasswordResetMethodResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOrUpdatePasswordResetMethodResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EmptyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
